version: '3.3'
services:
  node:
    image: node
    container_name: node
    command: >
      sh -c "npm i
             npm run dev"
#    build:
#      context: /app
    working_dir: /app
    restart: unless-stopped
    ports:
      - 3000:8080
    volumes:
      - .:/app
    depends_on:
      - mongo
    
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
